<?php
/**
 * Tablero de avance del proyecto Automarket — fuente de datos versionada.
 * Actualizar manualmente al cerrar o avanzar un bloque del roadmap.
 *
 * @return array<string, mixed>
 */
return [
    'meta' => [
        'titulo'           => 'Tablero de avance Automarket',
        'version_tablero'  => 'AM-CONT-4C-B3-B',
        'fecha_actualizacion' => '2026-07-03',
        'nota_porcentajes' => 'Los porcentajes son estimaciones de auditoría interna, no métricas exactas ni KPIs de producción.',
        'metodologia_estados' => 'La funcionalidad no se bloquea por falta de contenido de mercadeo. Separar: En diagnóstico, Diagnóstico aprobado, Pendiente funcional, Módulo listo / contenido pendiente, Bloqueado por decisión de negocio, Bloqueado por dato externo, Cerrado producción.',
    ],

    'resumen' => [
        'avance_global'     => 81,
        'seo_tecnico'       => 84,
        'cms_editorial'     => 93,
        'ux_conversion'     => 64,
        'contenido_aeo_geo' => 69,
    ],

    'pendientes_funcionales' => [],

    'modulos_contenido_pendiente' => [
        ['item' => 'Blog / noticias / novedades RAC', 'nota' => 'Infraestructura funcional cerrada (AM-CONT-4C-A): listados /blog.php, /noticias.php, /contenido-reciente.php y detalle noticia.php; schema Article/NewsArticle/BlogPosting; sitemap filtra demo/no publicados. Noticias RAC con contenido real; blog/novedades pendientes de contenido final o reemplazo de demo. Mercadeo publica desde admin; sin inventar contenido ni tocar site_data.json.'],
        ['item' => 'FAQ institucional por unidad', 'nota' => 'Infraestructura funcional existente: FAQ institucional en /pagina-institucional.php?p=faq (admin HTML libre; footer y sitemap enlazan); FAQ por unidad estructurado {question,answer} en RAC/Leasing/Renting/Seminuevos/Taller; FAQPage schema condicional. Falta contenido final de Mercadeo; no se inventó contenido ni se tocó site_data.json.'],
        ['item' => 'Contenido leasing/renting legacy posts', 'nota' => 'Infraestructura diagnosticada (AM-CONT-6F): posts[] legacy fuente pública en leasing.php/renting.php; content.blog[] canal/migración paralela vía UnitContentService::migrateLegacyPostsToBlog() y flag _migrated_from_posts; CRUD admin Leasing/Renting existente. Revisión/reemplazo editorial pendiente Mercadeo; sin inventar contenido ni tocar site_data.json.'],
    ],

    'bloqueados_decision_negocio' => [
        ['item' => 'CTAs redundantes en páginas clave', 'nota' => 'Requiere decisión de negocio antes de eliminar o consolidar botones duplicados.'],
        ['item' => 'Sostenibilidad vs Fundación', 'nota' => 'Sostenibilidad: página propia sostenibilidad.php (sin cambios AM-CMS-6C). Fundación: pendiente decisión negocio; sin ruta pública, footer, sitemap ni migración funda-am; sin inventar contenido.'],
        ['item' => 'Integración avanzada vacantes (API/automatización)', 'nota' => 'Futuro opcional; enlace oficial Konzerta en prod (AM-NEG-7B cerrado). No requerido actualmente.'],
        ['item' => 'Traducción ES/EN', 'nota' => 'Alcance y prioridad de páginas bilingües.'],
    ],

    'bloqueados_dato_externo' => [
        ['item' => 'TikTok URL real', 'nota' => 'Pendiente @ oficial en tiktok.com. FooterService excluye label/icon TikTok si la URL no es tiktok.com (AM-BUGS-4D-A).'],
        ['item' => 'Google Business Profile', 'nota' => 'Sin URL pública confirmada. No en sameAs. Slot documentado AM-AIO-6B; futuro: seo.global.verified_same_as_urls[].'],
        ['item' => 'Wikidata', 'nota' => 'Sin entidad Q confirmada. No en sameAs hasta URL wikidata.org validada por negocio.'],
        ['item' => 'Redes por unidad (RAC/Leasing/Renting/Semi/Taller)', 'nota' => 'social_links por unidad en CMS; no se mezclan al Organization global (solo footer grupo). Confirmar con Mercadeo si deben reflejarse.'],
    ],

    'bloqueados_negocio' => [],

    'evidencias' => [
        ['fecha' => '2026-07-02', 'texto' => 'Producción HEAD 1f8f317 antes de AM-SEO-4A'],
        ['fecha' => '2026-07-03', 'texto' => 'Producción HEAD b7746a0 después de AM-SEO-4A'],
        ['fecha' => '2026-07-03', 'texto' => 'Sitemap: 144 /autos/, 0 detalle.php?placa='],
        ['fecha' => '2026-07-03', 'texto' => 'Sitemap: 20 /sucursal/'],
        ['fecha' => '2026-07-03', 'texto' => 'Sitemap: 0 sucursal.php?slug='],
        ['fecha' => '2026-07-03', 'texto' => '/sucursal/tumba-muerto → HTTP 200 y canonical correcto'],
        ['fecha' => '2026-07-03', 'texto' => 'sostenibilidad.php title correcto y 0 AutoRental schema'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-SEO-4A validado: /detalle.php?placa=EO5144 → H1 TOYOTA HILUX 2025, 1 canonical amigable'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0A en prod HEAD 1fe318b — test 200, www 404, fuera de sitemap'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-BUGS-4D-A: FooterService filtra redes con plataforma/URL inconsistente y deduplica LinkedIn'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-BUGS-4D-A: menú Seminuevos garantiza /seminuevos-sucursales.php si CMS lo omitió'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-BUGS-4D-A cerrado prod HEAD d3f5c53 — menú/sucursales 200, copyright OK, 0 bi-tiktok inválido, venta-autos con Nuestras Sucursales'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-INV-4B local: nginx /autos/{slug}/{placa} → detalle.php; regla id() prioritaria y exclusión en placa'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-INV-4B cerrado prod HEAD fd0b5db — restart contenedor web (reload nginx no aplicó MD5); /autos/toyota-hilux-2025/eo5144 → 200, H1 TOYOTA HILUX 2025, canonical amigable'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-INV-4B prod: legacy /detalle.php?placa=EO5144 → 200; sitemap 144 /autos/, 0 detalle.php?placa=; sucursales 20 /sucursal/ intactas'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-A: CMS blog operativo; demo «Prueba» oculto en www; estado vacío blog; Article schema en noticia.php; sitemap solo publicados reales'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-A cerrado prod HEAD 16bb81e — blog 0 Prueba, noticia.php?id=1 NewsArticle, sitemap 10 noticia/0 prueba, AM-INV-4B EO5144 intacto'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-A local: unit-contact-cards + footer_contact en renting-contactos y contactos.php Seminuevos'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-A cerrado prod HEAD 17601fc — renting-contactos y contactos Seminuevos 200, WhatsApp/teléfono, formularios e imágenes intactos, EO5144 OK'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B0: diagnóstico footer — columns parcial (solo Recursos); also_know/social/pagos/contacto fijos; híbrido recomendado'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B0 cerrado — decisión opción C híbrida: builder solo columnas enlaces; redes/pagos/contactos/copyright/Conoce también módulos v1'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B1 local: FooterService normalizeColumns/getActiveColumns; legacy recursos; link_type/open_in derivados'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B1 cerrado prod HEAD aa87382 — páginas 200, footer intacto, EO5144/sitemap 144/20, sin Fatal/Parse'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B2 local: footer.php loop getActiveColumns; target blank solo open_in new; also_know/redes/pagos intactos'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B2 cerrado prod HEAD 46b0968 — footer Recursos 1 col/7 links, EO5144 OK, sitemap 144/20, sin Fatal/Parse'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B3 local: admin CRUD N columnas footer; pestaña Columnas; sanitize URL; recursos protegida'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B3 cerrado prod HEAD 80bb952 — deploy ff-only; smoke admin Columnas sin escritura; 11 rutas 200; EO5144/sitemap 144/20'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B0: diagnóstico títulos hardcodeados — 13 páginas; top CEO (Vehículos Disponibles, Anatomía Seminuevo, Ventajas Corporativas); sub-bloques 5B1–5B5'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B0 cerrado — diagnóstico aprobado; docs/am-cms-5b-diagnostico-titulos.md; próximo AM-CMS-5B2 Seminuevos'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B2 local: seminuevos hero/anatomía/inventario títulos CMS; admin Principal Venta de Autos; fallbacks conservadores'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B2 cerrado prod HEAD 8d14e8b — QA local guardar/vaciar/restaurar; deploy ff-only; php -l 5/5; venta-autos/inventario fallbacks OK; EO5144 H1+canonical; sitemap 147/0/20/0; admin Textos visibles sin escritura'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B1 local: RAC/flota fleet_section compartido, search_results.title, opiniones_section; admin Principal RAC; fallbacks conservadores'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B1 cerrado prod HEAD bd7e5d7 — deploy ff-only; php -l 5/5 contenedor app; rent-a-car/flota 200; fallbacks OK; sitemap 147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B3 local: leasing ventajas corporativas + lead/opiniones; renting/taller hero CTA; lrt-public-copy.php; fallbacks conservadores'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B3 cerrado prod HEAD 6d18635 — deploy ff-only; renting/leasing/taller 200; compose exec app php -l 6/6; sitemap 147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B4 local: contactos/sucursales títulos CMS; contact-locations-public-copy.php; RAC/renting/semi/grupo; fallbacks conservadores'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B4 cerrado prod HEAD 55b557c — deploy ff-only; compose exec app php -l 11/11; smoke contactos/sucursales 200; regresiones OK; sitemap 147/0/20/0; dashboard test 200/www 404; QA admin guardar/vaciar/fallback/restaurar OK'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B5: auditoría cierre epic — H1/intros principales CMS en 12 páginas auditadas; pendientes menores documentados backlog post-5B'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5B cerrado prod HEAD 980aed3 — epic 5B0–5B4 completos; helpers rentacar/seminuevos/lrt/contact-locations; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-AIO-6A local: Organization global JSON-LD + sameAs footer; parentOrganization unidades/sucursales; schema-organization-helper.php'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-AIO-6A cerrado prod HEAD a857c27 — deploy ff-only; compose exec app php -l 7/7; smoke páginas principales 200; JSON-LD Organization/sameAs/#organization OK; sitemap 147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0B: recalibración post 5B/6A — avance_global 72%; cms_editorial 88%; seo_tecnico 78%; contenido_aeo_geo 58%; epic 5B y 6A cerrados prod'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-AIO-6B: auditoría perfiles oficiales — sameAs footer FB/IG/LinkedIn; excluye #/cruces; slots GBP/Wikidata/TikTok; verified_same_as_urls[] vacío'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-AIO-6B cerrado prod HEAD a7d6393 — deploy ff-only; compose exec app php -l 2/2; smoke páginas principales 200; JSON-LD Organization/sameAs OK; GBP/Wikidata no inventados; sitemap 147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-NEG-7A local: trabaja-con-nosotros.php base; SEO/canonical; footer Recursos link; sitemap; sin Konzerta ni formulario'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-NEG-7A cerrado prod HEAD 2fbd0bd — deploy ff-only; compose exec app php -l 6/6; trabaja-con-nosotros 200; H1/canonical/mailto/footer OK; sitemap 1/147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-NEG-7B: enlace oficial Konzerta en trabaja-con-nosotros.php; CTA externo seguro; mailto secundario; sin scraping/DB'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-NEG-7B cerrado prod HEAD 9dc6856 — deploy ff-only; compose exec app php -l 2/2; trabaja-con-nosotros 200; CTA Konzerta URL exacta target/rel OK; sitemap 1/147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5C local: opiniones venta-autos; Destacados/Novedades unit-content; leasing-flota cabecera; admin mínimo; fallbacks conservadores'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5C cerrado prod HEAD f3e2143 — deploy ff-only; php -l 11/11; smoke venta-autos/inventario/leasing-flota 200; admin 302 login; fallbacks OK; sitemap 1/147/0/20/0; dashboard test 200/www 404'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0C: limpieza pendientes post-5C — removido Footer builder (5A-B cerrado) y post-5B de pendiente funcional; métricas 75/90/78/62 sin cambio'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0C cerrado prod HEAD df4e40a — deploy ff-only; compose exec app php -l OK; dashboard test 200/www 404; pendientes_funcionales limpiados; métricas 75/90/78/62 sin cambio'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-6C: diagnóstico opción C aprobado — Sostenibilidad página propia intacta; Fundación sin publicar; sin site_data/nginx/footer/sitemap; bloque en validación'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-6C cerrado prod HEAD ae1ed99 — deploy ff-only; php -l OK; dashboard test 200+noindex/www 404+noindex; Sostenibilidad intacta; Fundación sin publicar; sin site_data/nginx/footer/sitemap; métricas 75/90/78/62'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-6D: diagnóstico FAQ aprobado — infraestructura global/unidad existente; schema FAQPage condicional; contenido pendiente Mercadeo; sin tocar site_data ni código público'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-6D cerrado prod HEAD 082001d — deploy ff-only; php -l OK; dashboard test 200+noindex/www 404+noindex; FAQ global/unidad diagnosticado; contenido pendiente Mercadeo; sin site_data ni código público'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-6E: diagnóstico blog/noticias/novedades RAC aprobado — infraestructura CMS/listados/detalle/schema/sitemap existente; noticias con contenido real; blog/novedades pendientes Mercadeo; sin tocar site_data ni código público'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-6E cerrado prod HEAD 0066014 — deploy ff-only; php -l OK; dashboard test 200+noindex/www 404+noindex; blog/noticias/novedades RAC diagnosticado; noticias reales; blog/novedades pendientes Mercadeo; sin site_data ni código público'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0D: recalibración post 6C/6D/6E — avance_global 77%; cms_editorial 91%; contenido_aeo_geo 65%; seo_tecnico 78% y ux_conversion 64% sin cambio; módulos editoriales listos pero contenido Mercadeo pendiente.'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0D cerrado prod HEAD f755edd — deploy ff-only; php -l OK; dashboard test 200+noindex/www 404; métricas recalibradas avance_global 77, cms_editorial 91, contenido_aeo_geo 65, seo_tecnico 78, ux_conversion 64'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-6F: diagnóstico leasing/renting legacy posts aprobado — posts[] público; content.blog[] migración paralela; UnitContentService migrateLegacyPostsToBlog/_migrated_from_posts; smoke leasing/renting y detalles 200; contenido editorial pendiente Mercadeo; sin tocar site_data ni código público'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-6F cerrado prod HEAD 017dbd0 — diagnóstico leasing/renting legacy posts; posts[] público y content.blog migrado/paralelo documentados; UnitContentService migrateLegacyPostsToBlog/_migrated_from_posts identificado; smoke leasing/renting y detalles públicos validado; contenido editorial queda pendiente Mercadeo'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0E: alineación dashboard post AM-CONT-6F — estados obsoletos AM-DASH-0B/CMS base revisados; pendientes editoriales y bloqueos preservados; métricas conservadas 78/92/67/78/64'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0E cerrado prod HEAD 9f87101 — dashboard alineado post AM-CONT-6F; estados obsoletos AM-DASH-0B/CMS base revisados; pendientes editoriales y bloqueos de negocio preservados; métricas conservadas 78/92/67/78/64 por no haber cambios funcionales.'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-B0: diagnóstico formal meta/URLs blog/noticia — noticia.php?id documentado; slug no usado en URL/canonical/sitemap; meta derivada sin campos SEO dedicados; OG/schema presentes; B1–B4 definidos; B3 /blog/{slug}+301 requiere autorización explícita'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-B0 cerrado prod HEAD ebe9fb0 — diagnóstico formal meta/URLs blog/noticia; noticia.php?id actual documentado; slug almacenado no usado en URL/canonical/sitemap; meta derivada sin campos SEO dedicados; OG/schema presentes; /blog/{slug}+301 queda como B3 con autorización explícita.'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-B1 cerrado prod HEAD 0d5c7a0 — meta SEO dedicada por artículo implementada sin cambiar URLs; unit-content soporta meta_title/meta_description; admin edita título/descripción SEO; noticia.php usa meta dedicada con fallback; canonical noticia.php?id se mantiene; sin nginx, sin sitemap, sin redirects y sin tocar site_data.json.'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-B3-A cerrado prod HEAD 6e20f64 — resolución por slug en PHP implementada sin cambiar URLs públicas; noticia.php acepta slug con unit/type y mantiene prioridad id; canonical/sitemap/detailUrl/enlaces públicos siguen en noticia.php?id; sin nginx, sin 301, sin /blog/{unit}/{type}/{slug} y sin tocar site_data.json.'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-B3-B cerrado prod HEAD 1434146 — ruta limpia /blog/{unit}/{type}/{slug} habilitada vía nginx rewrite interno a noticia.php?unit/type/slug; validada 200 sin 301; canonical/sitemap/detailUrl/enlaces públicos permanecen en noticia.php?id; sin tocar site_data.json ni contenido editorial.'],
    ],

    'bloques' => [
        [
            'codigo'              => 'DB-INV-SYNC',
            'nombre'              => 'MariaDB / inventory-sync',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Sincronización de inventario con MariaDB y pipeline operativo en producción.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Inventario activo en prod (placas EO5144, EO6144, etc.).',
            'siguiente_accion'    => 'Mantener; no reabrir salvo incidente de sync.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3A',
            'nombre'              => 'SEO/UX quick wins',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Correcciones rápidas de SEO y UX detectadas en auditoría inicial.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Desplegado en prod.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-3B1',
            'nombre'              => 'CMS RAC',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mejoras CMS para Rent A Car en admin.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Admin operativo.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-3B2',
            'nombre'              => 'Controles por unidad',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Controles de contenido segmentados por unidad de negocio.',
            'dependencias'        => ['AM-CMS-3B1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Admin operativo.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-3B3',
            'nombre'              => 'Topbar / contactos por unidad',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Barra superior y contactos configurables por unidad.',
            'dependencias'        => ['AM-CMS-3B2'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Visible en frontend por unidad.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'HOTFIX-TEL-DASH',
            'nombre'              => 'Hotfix telemetry dashboard',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Corrección del dashboard de telemetría.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Desplegado.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'HOTFIX-TEL-INGEST',
            'nombre'              => 'Hotfix telemetry ingest',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Corrección del ingest de telemetría.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Desplegado.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3D1',
            'nombre'              => 'Sitemap / hreflang / schemas por unidad',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Sitemap dinámico, hreflang y schemas base por unidad.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'sitemap.php operativo.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'MICROFIX-SITEMAP',
            'nombre'              => 'Sitemap sin sesión/cookies',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Sitemap crawler-friendly sin PHPSESSID ni Cache-Control no-store.',
            'dependencias'        => ['AM-SEO-3D1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'sitemap.php sin session_start.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3D2-A',
            'nombre'              => 'Vehículos en sitemap',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Inclusión de fichas de vehículo en sitemap (144 URLs detalle).',
            'dependencias'        => ['AM-SEO-3D1', 'DB-INV-SYNC'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Sitemap: 144 detalle.php.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3C',
            'nombre'              => 'Sucursales / locations master',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Maestro de sucursales, LocalBusiness e ItemList. No tocar sin autorización.',
            'dependencias'        => [],
            'ultimo_commit'       => 'dcebc98',
            'evidencia'           => '20 /sucursal/ en sitemap; schemas LocalBusiness/ItemList.',
            'siguiente_accion'    => 'Cerrado — no reabrir.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3G-A',
            'nombre'              => 'URL amigable sucursal',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Rutas /sucursal/{slug} con dual-serve nginx.',
            'dependencias'        => ['AM-SEO-3C'],
            'ultimo_commit'       => '7449e72',
            'evidencia'           => '/sucursal/tumba-muerto → 200.',
            'siguiente_accion'    => 'Cerrado — no tocar nginx.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3G-B',
            'nombre'              => 'Canonical / sitemap / schema sucursal',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Canonical friendly, sitemap y schema en sucursales. Sin 301 legacy.',
            'dependencias'        => ['AM-SEO-3G-A'],
            'ultimo_commit'       => '1f8f317',
            'evidencia'           => 'Sitemap: 0 sucursal.php?slug=; canonical correcto.',
            'siguiente_accion'    => 'Cerrado — AM-SEO-3G-C pospuesto.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-4A',
            'nombre'              => 'Canonical global, titles, H1, FAQ schema',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Fallback canonical www, titles únicos, H1 en detalle, FAQPage condicional, sostenibilidad sin AutoRental.',
            'dependencias'        => ['AM-SEO-3G-B'],
            'ultimo_commit'       => 'b7746a0',
            'evidencia'           => 'EO5144: H1 TOYOTA HILUX 2025, canonical /autos/toyota-hilux-2025/eo5144.',
            'siguiente_accion'    => 'Cerrado tras validación prod.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-DASH-0A',
            'nombre'              => 'Tablero interno de avance',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Dashboard interno en test/localhost con project-progress.php versionado.',
            'dependencias'        => [],
            'ultimo_commit'       => '1fe318b',
            'evidencia'           => 'test.automarket.com.pa/avance-automarket.php → 200; www → 404; noindex.',
            'siguiente_accion'    => 'Recalibración AM-DASH-0B aplicada en project-progress.php.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-DASH-0B',
            'nombre'              => 'Recalibración general dashboard post 5B y 6A',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Actualización de avance_global y métricas por área tras cierre AM-CMS-5B (5B0–5B5) y AM-AIO-6A. Sin cambios de código público.',
            'dependencias'        => ['AM-CMS-5B', 'AM-AIO-6A'],
            'ultimo_commit'       => 'ed06b01',
            'evidencia'           => 'Resumen histórico: global 72%, cms_editorial 88%, seo_tecnico 78%, contenido_aeo_geo 58%, ux_conversion 64%. Bloques 5B0–5B5 y 6A cerrados prod. Superado por AM-DASH-0C, AM-DASH-0D y AM-DASH-0E.',
            'siguiente_accion'    => 'Cerrado. Superado por AM-DASH-0C, AM-DASH-0D y AM-DASH-0E.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-DASH-0C',
            'nombre'              => 'Limpieza de pendientes post 5C',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Baja',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Depuración dashboard: pendientes_funcionales sin ítems ya cerrados (5A-B, post-5B); módulos contenido y bloqueados alineados.',
            'dependencias'        => ['AM-CMS-5C'],
            'ultimo_commit'       => 'df4e40a',
            'evidencia'           => 'Prod df4e40a: deploy ff-only; compose exec app php -l OK; dashboard test 200/www 404; pendientes_funcionales vacío; métricas 75/90/78/62.',
            'siguiente_accion'    => 'Cerrado. Mantener backlog alineado tras epic 5C.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-DASH-0D',
            'nombre'              => 'Recalibración dashboard post 6C/6D/6E',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Recalibración de métricas tras cierre de Sostenibilidad/Fundación, FAQ y Blog/Noticias/Novedades RAC.',
            'dependencias'        => ['AM-CMS-6C', 'AM-CONT-6D', 'AM-CONT-6E'],
            'ultimo_commit'       => 'f755edd',
            'evidencia'           => 'Producción validada con deploy ff-only; php -l OK; dashboard test HTTP 200 + noindex; dashboard www HTTP 404 + noindex; métricas visibles avance_global 77, cms_editorial 91, contenido_aeo_geo 65, seo_tecnico 78, ux_conversion 64.',
            'siguiente_accion'    => 'Continuar con el próximo bloque del roadmap priorizado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-6C',
            'nombre'              => 'Sostenibilidad vs Fundación — arquitectura',
            'area'                => 'CMS editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Preparación opción C: Sostenibilidad como página propia sin cambios visibles; Fundación pendiente negocio; sin nueva ruta, footer, sitemap ni migración funda-am; sin inventar contenido ni tocar site_data.json.',
            'dependencias'        => ['AM-DASH-0C'],
            'ultimo_commit'       => 'ae1ed99',
            'evidencia'           => 'Prod ae1ed99: deploy ff-only OK; php -l OK; dashboard test 200+noindex/www 404+noindex; Sostenibilidad intacta; Fundación sin publicar; sin site_data/nginx/footer/sitemap; métricas 75/90/78/62.',
            'siguiente_accion'    => 'Cerrado. Esperar decisión de negocio sobre arquitectura Fundación; futuro sprint CMS sostenibilidad opcional solo con contenido aprobado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-INV-4B',
            'nombre'              => 'URL amigable vehículo',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Rutas /autos/{slug}/{placa} vía nginx; legacy /detalle.php?placa= viva; sitemap y canonical alineados.',
            'dependencias'        => ['AM-SEO-4A'],
            'ultimo_commit'       => 'fd0b5db',
            'evidencia'           => 'Prod fd0b5db: EO5144 legacy 200 y /autos/toyota-hilux-2025/eo5144 200, H1 TOYOTA HILUX 2025, canonical amigable, 0 errores; sitemap 144 /autos/, 0 detalle.php?placa=; restart web tras MD5 host≠contenedor.',
            'siguiente_accion'    => 'Cerrado. Deploy nginx: verificar MD5 host vs contenedor; si reload no aplica, restart solo contenedor web.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-A',
            'nombre'              => 'Módulo blog/contenido listo para mercadeo',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'CMS blog/noticias/novedades operativo; demo oculto en www; estado vacío profesional; Article/BlogPosting schema; sitemap solo publicados reales; isDemoContent conservador.',
            'dependencias'        => ['AM-SEO-4A'],
            'ultimo_commit'       => '16bb81e',
            'evidencia'           => 'Prod 16bb81e: blog 0 Prueba + estado vacío; noticia.php?id=1 → 200 NewsArticle; sitemap 10 noticia/0 prueba/144 autos/20 sucursal; EO5144 intacto; filtro demo no bloquea «Prueba de manejo».',
            'siguiente_accion'    => 'Cerrado. Mercadeo publica desde admin. Futuro opcional: meta por artículo, URLs /blog/{slug}, redirect blog.php?id→noticia.php.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C',
            'nombre'              => 'Contenido editorial SEO (epic)',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Módulo listo / contenido pendiente Mercadeo',
            'porcentaje_estimado' => 65,
            'descripcion'         => 'Epic: módulo funcional cerrado en AM-CONT-4C-A; AM-CONT-4C-B0 diagnóstico meta/URLs formalizado; AM-CONT-4C-B1 meta SEO dedicada cerrado; sub-bloques B2–B4 pendientes; contenido Mercadeo pendiente.',
            'dependencias'        => ['AM-CONT-4C-A'],
            'ultimo_commit'       => '16bb81e',
            'evidencia'           => '4C-A cerrado prod; AM-CONT-4C-B0 diagnóstico formal meta/URLs; AM-CONT-4C-B1 meta SEO dedicada por artículo sin cambiar URLs; AM-CONT-6D/6E/6F diagnosticados; artículos reales los carga mercadeo; ~10 noticia.php en sitemap.',
            'siguiente_accion'    => 'Mercadeo publica contenido real; continuar AM-CONT-4C-B2 canonical/schema refinado sin URLs, o B3 /blog/{slug}+301 solo con autorización explícita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B0',
            'nombre'              => 'Diagnóstico formal meta/URLs blog/noticia',
            'area'                => 'SEO técnico / Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Diagnóstico SEO técnico / contenido AEO para artículos blog/noticia.',
            'dependencias'        => ['AM-CONT-4C', 'AM-CONT-4C-A', 'AM-DASH-0E'],
            'ultimo_commit'       => '0d5c7a0',
            'evidencia'           => 'Diagnóstico formal validado: noticia.php opera con detalle por id y type/unit opcional; blog.php existe pero en producción no muestra artículos blog publicados; noticias.php sí enlaza detalles noticia.php?id=...; los artículos tienen slug normalizado en datos/CMS pero no se usa en URL pública, canonical ni sitemap; meta title/description se derivan de title/excerpt/description y no existen campos SEO dedicados por artículo; canonical actual apunta a noticia.php?id=...; Open Graph y JSON-LD Article/NewsArticle/BlogPosting existen; cambio a /blog/{slug} requiere autorización explícita por impacto en rutas, canonical, sitemap y redirects 301. Restricciones: no implementar /blog/{slug} todavía; no tocar nginx; no tocar site_data.json; no cambiar canonical público ni sitemap todavía.',
            'siguiente_accion'    => 'Continuar con AM-CONT-4C-B2 canonical/schema refinado sin cambiar URLs, o AM-CONT-4C-B3 /blog/{slug}+301 solo con autorización explícita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B1',
            'nombre'              => 'Meta SEO dedicada por artículo sin cambiar URLs',
            'area'                => 'SEO técnico / Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'meta_title y meta_description opcionales por artículo en news/blog/latest; URL pública sigue noticia.php?id=...',
            'dependencias'        => ['AM-CONT-4C-B0'],
            'ultimo_commit'       => '0d5c7a0',
            'evidencia'           => 'Meta SEO dedicada por artículo implementada sin cambiar URLs: unit-content soporta meta_title/meta_description opcionales; admin permite editar título SEO y descripción SEO para news/blog/latest; noticia.php prioriza meta dedicada con fallback a title/excerpt/description actual; OG/schema conservan compatibilidad; canonical y URL pública noticia.php?id=... se mantienen sin cambios. No se tocó nginx, sitemap, site_data.json ni redirects.',
            'siguiente_accion'    => 'Continuar con AM-CONT-4C-B2 para canonical/schema refinado sin cambiar URLs, o mantener AM-CONT-4C-B3 pospuesto hasta autorización explícita para /blog/{slug}+301.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B2',
            'nombre'              => 'Canonical/schema refinado por artículo sin cambiar URLs',
            'area'                => 'SEO técnico / Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Pendiente funcional',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'Revisar canonical, OG y JSON-LD para artículos con la URL actual basada en id.',
            'dependencias'        => ['AM-CONT-4C-B1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Definido en AM-CONT-4C-B0; B1 cerrado; refinamiento canonical/OG/schema pendiente.',
            'siguiente_accion'    => 'Refinar canonical/OG/schema sobre noticia.php?id tras B1.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B3',
            'nombre'              => 'URLs amigables /blog/{slug} + redirects 301',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Baja',
            'estado'              => 'En desarrollo controlado por subciclos',
            'porcentaje_estimado' => 40,
            'descripcion'         => 'Epic URLs amigables por subciclos B3-A–B3-E; B3-A slug PHP y B3-B ruta limpia nginx cerrados; 301/canonical/sitemap pendientes B3-C/B3-D.',
            'dependencias'        => ['AM-CONT-4C-B0', 'AM-CONT-4C-B1'],
            'ultimo_commit'       => '1434146',
            'evidencia'           => 'B3-A resolución slug vía query; B3-B /blog/{unit}/{type}/{slug} 200 vía nginx rewrite sin 301 ni canonical nuevo. Pendiente B3-C 301 y B3-D canonical/sitemap/schema.',
            'siguiente_accion'    => 'Continuar AM-CONT-4C-B3-C 301 o AM-CONT-4C-B3-D canonical/sitemap/schema según estrategia SEO aprobada.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B3-A',
            'nombre'              => 'Resolver artículo por slug en PHP sin cambiar canonical/sitemap',
            'area'                => 'SEO técnico / Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'noticia.php acepta ?slug= con unit/type; prioridad id; canonical/sitemap/detailUrl sin cambios.',
            'dependencias'        => ['AM-CONT-4C-B3', 'AM-CONT-4C-B1'],
            'ultimo_commit'       => '6e20f64',
            'evidencia'           => 'Resolución por slug implementada en PHP como paso seguro previo a URLs amigables: noticia.php acepta slug opcional con unit/type, mantiene prioridad de id, conserva canonical/sitemap/detailUrl/enlaces públicos basados en noticia.php?id, y valida publicación/visibilidad sin tocar nginx ni redirects. URLs limpias /blog/{unit}/{type}/{slug} quedan para B3-B; 301 y canonical/sitemap nuevos quedan para B3-C/B3-D.',
            'siguiente_accion'    => 'Continuar con AM-CONT-4C-B3-B para rewrite/ruta limpia /blog/{unit}/{type}/{slug} en test, sin activar 301 ni cambiar canonical/sitemap hasta B3-C/B3-D.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B3-B',
            'nombre'              => 'Ruta limpia /blog/{unit}/{type}/{slug} sin 301 ni canonical nuevo',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Rewrite nginx /blog/{unit}/{type}/{slug} → noticia.php?unit&type&slug; HTTP 200; canonical/sitemap/detailUrl sin cambios.',
            'dependencias'        => ['AM-CONT-4C-B3-A'],
            'ultimo_commit'       => '1434146',
            'evidencia'           => 'Ruta limpia /blog/{unit}/{type}/{slug} habilitada vía nginx como rewrite interno hacia noticia.php?unit={unit}&type={type}&slug={slug}; validada con artículos RAC/news, leasing/blog y renting/blog. Se conserva canonical antiguo noticia.php?id=..., sitemap sin cambios, detailUrl/listados sin cambios y no se implementan redirects 301. B3-C/B3-D quedan pendientes para 301 y canonical/sitemap/schema/OG.',
            'siguiente_accion'    => 'Continuar con AM-CONT-4C-B3-C para redirects 301 desde URLs viejas solo cuando B3-B quede estable, o AM-CONT-4C-B3-D para canonical/sitemap/schema/OG hacia URL nueva según estrategia SEO aprobada.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B3-C',
            'nombre'              => 'Redirects 301 desde noticia.php?id hacia URL nueva',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Media',
            'estado'              => 'Pendiente funcional',
            'porcentaje_estimado' => 0,
            'descripcion'         => '301 desde URLs indexadas noticia.php?... hacia /blog/{unit}/{type}/{slug}.',
            'dependencias'        => ['AM-CONT-4C-B3-B'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Pendiente; ~10 URLs en sitemap.',
            'siguiente_accion'    => 'Implementar 301 solo para slugs únicos y publicados.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B3-D',
            'nombre'              => 'Canonical/sitemap/schema/OG a URL nueva',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Media',
            'estado'              => 'Pendiente funcional',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'detailUrl, SitemapService, canonical, schema y OG apuntan a URL amigable.',
            'dependencias'        => ['AM-CONT-4C-B3-B'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Pendiente tras B3-B.',
            'siguiente_accion'    => 'Actualizar detailUrl y collectPublishedContentUrls.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B3-E',
            'nombre'              => 'Cierre dashboard epic B3 URLs amigables',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Baja',
            'estado'              => 'Pendiente cierre dashboard',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'Cierre administrativo y recalibración tras B3-A–B3-D.',
            'dependencias'        => ['AM-CONT-4C-B3-A'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Pendiente de cierre tras subciclos B3-B–B3-D.',
            'siguiente_accion'    => 'Ejecutar tras completar migración URL amigable.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-B4',
            'nombre'              => 'Cierre/recalibración dashboard post meta/URLs',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Baja',
            'estado'              => 'Pendiente cierre dashboard',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'Cierre administrativo del epic AM-CONT-4C-B tras B1/B2/B3 según lo aprobado.',
            'dependencias'        => ['AM-CONT-4C-B1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'B1 cerrado; pendiente de cierre tras sub-bloques B2–B3 aprobados.',
            'siguiente_accion'    => 'Ejecutar tras completar sub-bloques técnicos aprobados.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-6D',
            'nombre'              => 'FAQ institucional por unidad',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Diagnóstico y documentación de infraestructura FAQ existente, sin cambios funcionales ni contenido inventado.',
            'dependencias'        => ['AM-CONT-4C-A'],
            'ultimo_commit'       => '082001d',
            'evidencia'           => 'Prod 082001d: deploy ff-only OK; php -l OK; dashboard test 200+noindex/www 404+noindex; FAQ institucional y FAQ por unidad diagnosticados; FAQPage schema condicional existente; contenido pendiente Mercadeo; sin tocar site_data ni código público.',
            'siguiente_accion'    => 'Cerrado. Mercadeo debe cargar contenido final FAQ desde admin; futuro ajuste UX/schema solo si negocio lo solicita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-6E',
            'nombre'              => 'Blog / noticias / novedades RAC',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Diagnóstico e inventario editorial de blog/noticias/novedades RAC; infraestructura existente; sin cambios funcionales ni contenido inventado.',
            'dependencias'        => ['AM-CONT-4C-A', 'AM-CONT-6D'],
            'ultimo_commit'       => '0066014',
            'evidencia'           => 'Prod 0066014: deploy ff-only OK; php -l OK; dashboard test 200+noindex/www 404+noindex; blog/noticias/novedades diagnosticados; noticias RAC con contenido real; blog/novedades pendientes Mercadeo; sin tocar site_data ni código público.',
            'siguiente_accion'    => 'Cerrado. Mercadeo debe cargar/reemplazar contenido final de blog y novedades desde admin; futuro ajuste URLs/meta solo si negocio lo solicita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-6F',
            'nombre'              => 'Contenido leasing/renting legacy posts',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Diagnóstico de infraestructura editorial y migración legacy posts.',
            'dependencias'        => ['AM-CONT-6E', 'AM-DASH-0D'],
            'ultimo_commit'       => '017dbd0',
            'evidencia'           => 'Diagnóstico producción validado: Leasing/Renting mantienen publicaciones legacy posts[] como fuente pública; content.blog[] existe como canal/migración paralela mediante UnitContentService::migrateLegacyPostsToBlog() y flag _migrated_from_posts; rutas públicas leasing.php/renting.php y detalles leasing-publicacion.php/renting-publicacion.php validadas sin modificar datos; CRUD/admin existente; riesgo de divergencia editorial documentado. Contenido final/revisión queda pendiente de Mercadeo.',
            'siguiente_accion'    => 'Continuar con el próximo bloque priorizado del roadmap sin unificar legacy posts y content.blog hasta aprobación explícita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-DASH-0E',
            'nombre'              => 'Recalibración y alineación dashboard post 6F',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Housekeeping del tablero tras cierre AM-CONT-6F: alineación de estados heredados/obsoletos sin cambio funcional.',
            'dependencias'        => ['AM-CONT-6F', 'AM-DASH-0D'],
            'ultimo_commit'       => '9f87101',
            'evidencia'           => 'Dashboard alineado tras cierre AM-CONT-6F: se consolidan estados obsoletos/heredados del tablero, se preservan bloqueos de negocio y datos externos, se mantienen pendientes editoriales de Mercadeo sin tocar contenido ni site_data.json. Métricas conservadas por tratarse de ordenamiento administrativo sin cambio funcional.',
            'siguiente_accion'    => 'Continuar con sprint técnico opcional AM-CONT-4C-B de URLs/meta por artículo solo con autorización explícita; si no, esperar insumos de Mercadeo para pendientes editoriales y datos externos.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-BUGS-4D-A',
            'nombre'              => 'Quick wins footer, menú Seminuevos, sucursales',
            'area'                => 'UX/conversión',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Copyright sin año duplicado, redes sociales coherentes, menú Seminuevos con sucursales, sección sucursales en venta-autos.',
            'dependencias'        => [],
            'ultimo_commit'       => 'd3f5c53',
            'evidencia'           => 'Prod: seminuevos-sucursales 200, menú con /seminuevos-sucursales.php, venta-autos Nuestras Sucursales, © único, 0 TikTok inválido.',
            'siguiente_accion'    => 'Cerrado. TikTok URL real y CTAs siguen en bloqueados_negocio.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-BUGS-4D',
            'nombre'              => 'TikTok, copyright, menú Seminuevos, CTAs',
            'area'                => 'UX/conversión',
            'prioridad'           => 'Media',
            'estado'              => 'Bloqueado por decisión de negocio',
            'porcentaje_estimado' => 50,
            'descripcion'         => 'Epic UX: quick wins cerrados en AM-BUGS-4D-A; pendiente TikTok URL real y decisión CTAs.',
            'dependencias'        => ['AM-BUGS-4D-A'],
            'ultimo_commit'       => 'd3f5c53',
            'evidencia'           => '4D-A en prod; TikTok/CTAs en bloqueados_negocio.',
            'siguiente_accion'    => 'Esperar marketing (TikTok) y decisión negocio (CTAs).',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-A',
            'nombre'              => 'Contactos completos Seminuevos y Renting',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mostrar teléfono, WhatsApp, email y horario desde footer_contact en renting-contactos.php y contactos.php (Seminuevos).',
            'dependencias'        => ['AM-CMS-3B3'],
            'ultimo_commit'       => '17601fc',
            'evidencia'           => 'Prod 17601fc: renting-contactos y contactos?unit=seminuevos → 200; tel/WhatsApp desde footer_contact; 2 bloques contacto responsive (desktop+móvil); formularios e imágenes OK; sitemap/EO5144 intactos.',
            'siguiente_accion'    => 'Cerrado prod. Contactos en admin unidad.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B0',
            'nombre'              => 'Diagnóstico footer builder por columnas',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mapa técnico footer: datos, admin, render, riesgos. Decisión aprobada opción C híbrida conservadora.',
            'dependencias'        => ['AM-CMS-5A-A'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Diagnóstico base absorbido por sub-bloques CMS posteriores ya validados. Builder solo columnas enlaces (N cols); v1 mantiene redes, pagos, contactos, copyright y Conoce también como módulos separados.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A',
            'nombre'              => 'CMS Seminuevos-Renting (epic)',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Epic funcional en producción / contenido pendiente',
            'porcentaje_estimado' => 85,
            'descripcion'         => 'Epic CMS Seminuevos-Renting: 5A-B footer cerrado prod; epic 5B títulos editables cerrado prod (980aed3).',
            'dependencias'        => ['AM-CMS-3B3'],
            'ultimo_commit'       => '980aed3',
            'evidencia'           => 'Sub-bloques CMS principales cerrados en producción; pendientes restantes dependen de contenido/decisiones de negocio o Mercadeo. 5A-B0–B3 cerrados prod; epic 5B B0–5B5 cerrado; B4 55b557c.',
            'siguiente_accion'    => 'Epic funcional cerrado en prod; pendientes editoriales/negocio vía modulos_contenido_pendiente y bloqueados.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B',
            'nombre'              => 'Footer builder columnas de enlaces',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Builder N columnas enlaces: B1 normalización, B2 render, B3 admin CRUD; recursos protegida; módulos also_know/redes/pagos v1 separados.',
            'dependencias'        => ['AM-CMS-5A-B0'],
            'ultimo_commit'       => '80bb952',
            'evidencia'           => 'Prod 80bb952: pestaña Columnas CRUD; sanitizeFooterUrl; smoke admin sin escritura; footer/sitemap/EO5144 intactos.',
            'siguiente_accion'    => 'Cerrado producción. Epic AM-CMS-5B completado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B1',
            'nombre'              => 'Normalización FooterService columnas',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Backend N columnas: normalizeColumns, getActiveColumns, link_type/open_in, legacy recursos, sin admin ni render público.',
            'dependencias'        => ['AM-CMS-5A-B0'],
            'ultimo_commit'       => 'aa87382',
            'evidencia'           => 'Prod aa87382: php -l OK; páginas 200; footer Recursos/Conoce también intacto; EO5144 H1+canonical; sitemap 144/0/20/0.',
            'siguiente_accion'    => 'Cerrado. B2 render dinámico cerrado prod.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B2',
            'nombre'              => 'Render dinámico columnas en footer.php',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'footer.php usa getActiveColumns(); loop N columnas; target blank solo open_in new; módulos also_know/social/pagos/copyright intactos.',
            'dependencias'        => ['AM-CMS-5A-B1'],
            'ultimo_commit'       => '46b0968',
            'evidencia'           => 'Prod 46b0968: Recursos 1 col/7 links; internos sin target blank; EO5144 200 H1+canonical; sitemap 144/0/20/0; 10 rutas 200.',
            'siguiente_accion'    => 'Cerrado. B3 admin CRUD cerrado prod.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B3',
            'nombre'              => 'Admin CRUD columnas footer',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Pestaña Columnas: CRUD N columnas y links; footer.columns; recursos protegida; sanitize URLs protocol-relative.',
            'dependencias'        => ['AM-CMS-5A-B2'],
            'ultimo_commit'       => '80bb952',
            'evidencia'           => 'Prod 80bb952: deploy ff-only; php -l 4/4; smoke admin Columnas sin escritura (recursos protegida, add col/link); 11 rutas 200; footer Recursos/Conoce también; EO5144 H1+canonical; sitemap 144/0/20/0; javascript/data/vbscript 0.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B0',
            'nombre'              => 'Diagnóstico títulos/subtítulos hardcodeados',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Diagnóstico aprobado',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mapeo read-only de h1–h4, intros, CTAs y labels en 13 páginas/familias; clasificación C1–C5; sub-bloques 5B1–5B5 definidos.',
            'dependencias'        => ['AM-CMS-5A-B'],
            'ultimo_commit'       => '6695461',
            'evidencia'           => 'docs/am-cms-5b-diagnostico-titulos.md aprobado; ~100 C2; primer sprint 5B2 Seminuevos (anatomía, hero_title).',
            'siguiente_accion'    => 'Cerrado diagnóstico. B2 Seminuevos cerrado prod.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B',
            'nombre'              => 'Control ampliado títulos / subtítulos / textos',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Epic títulos editables cerrado. B0 diagnóstico; B1 RAC/flota; B2 seminuevos; B3 LRT; B4 contactos/sucursales; B5 cierre y auditoría. Helpers: rentacar-public-copy, seminuevos-public-copy, lrt-public-copy, contact-locations-public-copy.',
            'dependencias'        => ['AM-CMS-5A-B'],
            'ultimo_commit'       => '555458a',
            'evidencia'           => 'Prod 980aed3: B1 bd7e5d7; B2 8d14e8b; B3 6d18635; B4 55b557c; B5 auditoría H1/intros principales OK en páginas epic; backlog menor documentado.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B5',
            'nombre'              => 'Cierre epic AM-CMS-5B',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Auditoría final ligera epic 5B; confirmación B0–5B4 en dashboard; backlog post-5B documentado sin implementación.',
            'dependencias'        => ['AM-CMS-5B4'],
            'ultimo_commit'       => '555458a',
            'evidencia'           => 'Auditoría 12 páginas: H1/intros principales CMS o fallback; pendientes menores (opiniones venta-autos, Destacados/Novedades includes, leasing-flota) → backlog futuro.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5C',
            'nombre'              => 'Títulos/subtítulos secundarios post-5B',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Opiniones venta-autos (seminuevos opiniones_section); Destacados/Novedades home unit-content; leasing-flota cabecera; fallbacks + admin mínimo.',
            'dependencias'        => ['AM-CMS-5B'],
            'ultimo_commit'       => 'f3e2143',
            'evidencia'           => 'Prod f3e2143: deploy ff-only; php -l 11/11; smoke venta-autos/inventario/leasing-flota/rent-a-car 200; admin 302 login; fallbacks opiniones/Destacados/Novedades/leasing-flota OK; sitemap 1/147/0/20/0; dashboard test 200/www 404.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B4',
            'nombre'              => 'Contactos / Sucursales títulos y textos visibles editables',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'contactos.php RAC/semi/leasing/renting; sucursales.php RAC; renting-sucursales.php; sucursales-grupo.php; contact-locations-public-copy.php; admin textos visibles.',
            'dependencias'        => ['AM-CMS-5B0'],
            'ultimo_commit'       => '55b557c',
            'evidencia'           => 'Prod 55b557c: deploy ff-only; compose exec app php -l 11/11; smoke contactos/sucursales 200; regresiones OK; sitemap 147/0/20/0; dashboard test 200/www 404; QA admin guardar/vaciar/fallback/restaurar OK.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B3',
            'nombre'              => 'Leasing / Renting / Taller títulos y secciones editables',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'leasing.php ventajas corporativas + lead/opiniones; renting/taller hero CTA; campos principales ya CMS en renting/taller; lrt-public-copy.php.',
            'dependencias'        => ['AM-CMS-5B0'],
            'ultimo_commit'       => '6d18635',
            'evidencia'           => 'Prod 6d18635: deploy ff-only; renting/leasing/taller 200; compose exec app php -l 6/6; sitemap 147/0/20/0; dashboard test 200/www 404; admin Textos visibles — Leasing + hero CTA renting/taller.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B1',
            'nombre'              => 'RAC + flota.php títulos y secciones editables',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'rent-a-car.php + flota.php: fleet_section compartido, search_results.title, opiniones_section; admin tab Hero RAC; fallbacks actuales.',
            'dependencias'        => ['AM-CMS-5B0'],
            'ultimo_commit'       => 'bd7e5d7',
            'evidencia'           => 'Prod bd7e5d7: deploy ff-only; docker exec automarket_app php -l 5/5; rent-a-car/flota 200; fallbacks Vehículos Disponibles/Flota OK; sitemap 147/0/20/0; dashboard test 200/www 404; admin Textos visibles — Rent A Car.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B2',
            'nombre'              => 'Seminuevos títulos y secciones editables',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'venta-autos.php + inventario.php: hero, anatomía, badge inventario, títulos página inventario; admin semi-home; fallbacks actuales.',
            'dependencias'        => ['AM-CMS-5B0'],
            'ultimo_commit'       => '8d14e8b',
            'evidencia'           => 'Prod 8d14e8b: deploy ff-only; php -l 5/5; QA local guardar/vaciar/restaurar site_data; venta-autos fallbacks Anatomía/Hero OK; inventario 200; EO5144 H1+canonical; sitemap 147/0/20/0; admin Textos visibles — Venta de Autos smoke sin escritura.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-AIO-6A',
            'nombre'              => 'Organization schema sameAs / GBP / Wikidata',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Organization global JSON-LD en todas las páginas; sameAs desde redes footer CMS; parentOrganization en unidades y sucursales; pendiente GBP/Wikidata sin URL verificada.',
            'dependencias'        => ['AM-SEO-4A'],
            'ultimo_commit'       => 'a857c27',
            'evidencia'           => 'Prod a857c27: deploy ff-only; compose exec app php -l 7/7; smoke rent-a-car/venta-autos/renting/leasing/taller/sucursales/EO5144 200; JSON-LD Organization 1× + sameAs + #organization; sitemap 147/0/20/0; dashboard test 200/www 404.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-AIO-6B',
            'nombre'              => 'Perfiles oficiales / sameAs pendientes / entidad GEO',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Auditoría redes footer → sameAs (FB/IG/LinkedIn verificadas); filtros FooterService; slots GBP/Wikidata/TikTok documentados; estructura seo.global.verified_same_as_urls[] sin URLs inventadas.',
            'dependencias'        => ['AM-AIO-6A'],
            'ultimo_commit'       => 'a7d6393',
            'evidencia'           => 'Prod a7d6393: deploy ff-only; compose exec app php -l 2/2; smoke rent-a-car/venta-autos/renting/leasing/taller/sucursales 200; JSON-LD Organization 1× + sameAs; GBP/Wikidata ausentes; sitemap 147/0/20/0; dashboard test 200/www 404.',
            'siguiente_accion'    => 'Cerrado producción. GBP/Wikidata/TikTok cuando Mercadeo confirme URLs → verified_same_as_urls[].',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-NEG-7A',
            'nombre'              => 'Vacantes / Trabaja con Nosotros — módulo público base',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Página pública trabaja-con-nosotros.php con H1, intro, estado sin vacantes y CTA mailto global; footer Recursos; sitemap; sin Konzerta/DB/formulario.',
            'dependencias'        => [],
            'ultimo_commit'       => '2fbd0bd',
            'evidencia'           => 'Prod 2fbd0bd: deploy ff-only; compose exec app php -l 6/6; trabaja-con-nosotros/rent-a-car/venta-autos 200; H1/canonical/mailto info@automarket.com.pa; footer Recursos OK; sitemap 1/147/0/20/0; dashboard test 200/www 404.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-NEG-7B',
            'nombre'              => 'Konzerta — enlace externo oficial vacantes',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'CTA en trabaja-con-nosotros.php hacia Konzerta (URL oficial grupo); target blank + noopener; mailto secundario; sin listado ni scraping en sitio.',
            'dependencias'        => ['AM-NEG-7A'],
            'ultimo_commit'       => '9dc6856',
            'evidencia'           => 'Prod 9dc6856: deploy ff-only; compose exec app php -l 2/2; trabaja-con-nosotros 200; CTA Konzerta empleos-busqueda-panama-car-rental target/rel OK; mailto secundario; sitemap 1/147/0/20/0; dashboard test 200/www 404.',
            'siguiente_accion'    => 'Cerrado producción.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3G-C',
            'nombre'              => '301 sucursal.php?slug= → /sucursal/{slug}',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Baja',
            'estado'              => 'Pospuesto',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'Redirección 301 desde URL legacy de sucursal. Explícitamente pospuesto.',
            'dependencias'        => ['AM-SEO-3G-B'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Sitemap ya sin sucursal.php?slug=.',
            'siguiente_accion'    => 'No implementar sin autorización explícita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
    ],
];
