<?php
/**
 * Tablero de avance del proyecto Automarket — fuente de datos versionada.
 * Actualizar manualmente al cerrar o avanzar un bloque del roadmap.
 *
 * @return array<string, mixed>
 */
return [
    'meta' => [
        'titulo'           => 'Tablero de avance Automarket',
        'version_tablero'  => 'AM-CMS-5A-B2',
        'fecha_actualizacion' => '2026-07-03',
        'nota_porcentajes' => 'Los porcentajes son estimaciones de auditoría interna, no métricas exactas ni KPIs de producción.',
        'metodologia_estados' => 'La funcionalidad no se bloquea por falta de contenido de mercadeo. Separar: En diagnóstico, Diagnóstico aprobado, Pendiente funcional, Módulo listo / contenido pendiente, Bloqueado por decisión de negocio, Bloqueado por dato externo, Cerrado producción.',
    ],

    'resumen' => [
        'avance_global'     => 60,
        'seo_tecnico'       => 72,
        'cms_editorial'     => 63,
        'ux_conversion'     => 64,
        'contenido_aeo_geo' => 45,
    ],

    'pendientes_funcionales' => [
        ['item' => 'Vacantes / Trabaja con nosotros (sección base)', 'nota' => 'Falta módulo público de vacantes antes de integrar Konzerta.'],
        ['item' => 'Footer builder columnas (AM-CMS-5A-B)', 'nota' => 'Tras diagnóstico B0: N columnas de enlaces; redes/pagos/contactos/copyright como módulos existentes.'],
        ['item' => 'Títulos/subtítulos ampliados (AM-CMS-5B)', 'nota' => 'Mapear campos faltantes por página.'],
    ],

    'modulos_contenido_pendiente' => [
        ['item' => 'Blog / noticias / novedades RAC', 'nota' => 'Módulo funcional cerrado (AM-CONT-4C-A prod). Mercadeo publica artículos finales desde admin.'],
        ['item' => 'FAQ institucional por unidad', 'nota' => 'Admin permite editar preguntas; faltan respuestas definitivas de negocio. FAQPage schema funcional donde aplica.'],
        ['item' => 'Contenido leasing/renting legacy posts', 'nota' => 'Publicaciones migradas a content.blog; mercadeo puede reemplazar ejemplos.'],
    ],

    'bloqueados_decision_negocio' => [
        ['item' => 'CTAs redundantes en páginas clave', 'nota' => 'Requiere decisión de negocio antes de eliminar o consolidar botones duplicados.'],
        ['item' => 'Sostenibilidad vs Fundación', 'nota' => 'Definir arquitectura de páginas y mensajes institucionales. CMS editable debe existir donde aplique.'],
        ['item' => 'Konzerta / Trabaja con nosotros', 'nota' => 'Decisión de integración o enlace externo tras existir sección base.'],
        ['item' => 'Traducción ES/EN', 'nota' => 'Alcance y prioridad de páginas bilingües.'],
    ],

    'bloqueados_dato_externo' => [
        ['item' => 'TikTok URL real', 'nota' => 'Pendiente URL oficial validada por marketing. Código filtra entradas TikTok con URL de otra plataforma.'],
        ['item' => 'Google Business Profile / Wikidata', 'nota' => 'URLs sameAs y perfiles verificados para Organization schema.'],
    ],

    'bloqueados_negocio' => [],

    'evidencias' => [
        ['fecha' => '2026-07-02', 'texto' => 'Producción HEAD 1f8f317 antes de AM-SEO-4A'],
        ['fecha' => '2026-07-03', 'texto' => 'Producción HEAD b7746a0 después de AM-SEO-4A'],
        ['fecha' => '2026-07-03', 'texto' => 'Sitemap: 144 /autos/, 0 detalle.php?placa='],
        ['fecha' => '2026-07-03', 'texto' => 'Sitemap: 20 /sucursal/'],
        ['fecha' => '2026-07-03', 'texto' => 'Sitemap: 0 sucursal.php?slug='],
        ['fecha' => '2026-07-03', 'texto' => '/sucursal/tumba-muerto → HTTP 200 y canonical correcto'],
        ['fecha' => '2026-07-03', 'texto' => 'sostenibilidad.php title correcto y 0 AutoRental schema'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-SEO-4A validado: /detalle.php?placa=EO5144 → H1 TOYOTA HILUX 2025, 1 canonical amigable'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-DASH-0A en prod HEAD 1fe318b — test 200, www 404, fuera de sitemap'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-BUGS-4D-A: FooterService filtra redes con plataforma/URL inconsistente y deduplica LinkedIn'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-BUGS-4D-A: menú Seminuevos garantiza /seminuevos-sucursales.php si CMS lo omitió'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-BUGS-4D-A cerrado prod HEAD d3f5c53 — menú/sucursales 200, copyright OK, 0 bi-tiktok inválido, venta-autos con Nuestras Sucursales'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-INV-4B local: nginx /autos/{slug}/{placa} → detalle.php; regla id() prioritaria y exclusión en placa'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-INV-4B cerrado prod HEAD fd0b5db — restart contenedor web (reload nginx no aplicó MD5); /autos/toyota-hilux-2025/eo5144 → 200, H1 TOYOTA HILUX 2025, canonical amigable'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-INV-4B prod: legacy /detalle.php?placa=EO5144 → 200; sitemap 144 /autos/, 0 detalle.php?placa=; sucursales 20 /sucursal/ intactas'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-A: CMS blog operativo; demo «Prueba» oculto en www; estado vacío blog; Article schema en noticia.php; sitemap solo publicados reales'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CONT-4C-A cerrado prod HEAD 16bb81e — blog 0 Prueba, noticia.php?id=1 NewsArticle, sitemap 10 noticia/0 prueba, AM-INV-4B EO5144 intacto'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-A local: unit-contact-cards + footer_contact en renting-contactos y contactos.php Seminuevos'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-A cerrado prod HEAD 17601fc — renting-contactos y contactos Seminuevos 200, WhatsApp/teléfono, formularios e imágenes intactos, EO5144 OK'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B0: diagnóstico footer — columns parcial (solo Recursos); also_know/social/pagos/contacto fijos; híbrido recomendado'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B0 cerrado — decisión opción C híbrida: builder solo columnas enlaces; redes/pagos/contactos/copyright/Conoce también módulos v1'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B1 local: FooterService normalizeColumns/getActiveColumns; legacy recursos; link_type/open_in derivados'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B1 cerrado prod HEAD aa87382 — páginas 200, footer intacto, EO5144/sitemap 144/20, sin Fatal/Parse'],
        ['fecha' => '2026-07-03', 'texto' => 'AM-CMS-5A-B2 local: footer.php loop getActiveColumns; target blank solo open_in new; also_know/redes/pagos intactos'],
    ],

    'bloques' => [
        [
            'codigo'              => 'DB-INV-SYNC',
            'nombre'              => 'MariaDB / inventory-sync',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Sincronización de inventario con MariaDB y pipeline operativo en producción.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Inventario activo en prod (placas EO5144, EO6144, etc.).',
            'siguiente_accion'    => 'Mantener; no reabrir salvo incidente de sync.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3A',
            'nombre'              => 'SEO/UX quick wins',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Correcciones rápidas de SEO y UX detectadas en auditoría inicial.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Desplegado en prod.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-3B1',
            'nombre'              => 'CMS RAC',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mejoras CMS para Rent A Car en admin.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Admin operativo.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-3B2',
            'nombre'              => 'Controles por unidad',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Controles de contenido segmentados por unidad de negocio.',
            'dependencias'        => ['AM-CMS-3B1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Admin operativo.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-3B3',
            'nombre'              => 'Topbar / contactos por unidad',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Barra superior y contactos configurables por unidad.',
            'dependencias'        => ['AM-CMS-3B2'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Visible en frontend por unidad.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'HOTFIX-TEL-DASH',
            'nombre'              => 'Hotfix telemetry dashboard',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Corrección del dashboard de telemetría.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Desplegado.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'HOTFIX-TEL-INGEST',
            'nombre'              => 'Hotfix telemetry ingest',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Corrección del ingest de telemetría.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Desplegado.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3D1',
            'nombre'              => 'Sitemap / hreflang / schemas por unidad',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Sitemap dinámico, hreflang y schemas base por unidad.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'sitemap.php operativo.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'MICROFIX-SITEMAP',
            'nombre'              => 'Sitemap sin sesión/cookies',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Sitemap crawler-friendly sin PHPSESSID ni Cache-Control no-store.',
            'dependencias'        => ['AM-SEO-3D1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'sitemap.php sin session_start.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3D2-A',
            'nombre'              => 'Vehículos en sitemap',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Inclusión de fichas de vehículo en sitemap (144 URLs detalle).',
            'dependencias'        => ['AM-SEO-3D1', 'DB-INV-SYNC'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Sitemap: 144 detalle.php.',
            'siguiente_accion'    => 'Cerrado.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3C',
            'nombre'              => 'Sucursales / locations master',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Maestro de sucursales, LocalBusiness e ItemList. No tocar sin autorización.',
            'dependencias'        => [],
            'ultimo_commit'       => 'dcebc98',
            'evidencia'           => '20 /sucursal/ en sitemap; schemas LocalBusiness/ItemList.',
            'siguiente_accion'    => 'Cerrado — no reabrir.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3G-A',
            'nombre'              => 'URL amigable sucursal',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Rutas /sucursal/{slug} con dual-serve nginx.',
            'dependencias'        => ['AM-SEO-3C'],
            'ultimo_commit'       => '7449e72',
            'evidencia'           => '/sucursal/tumba-muerto → 200.',
            'siguiente_accion'    => 'Cerrado — no tocar nginx.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3G-B',
            'nombre'              => 'Canonical / sitemap / schema sucursal',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Canonical friendly, sitemap y schema en sucursales. Sin 301 legacy.',
            'dependencias'        => ['AM-SEO-3G-A'],
            'ultimo_commit'       => '1f8f317',
            'evidencia'           => 'Sitemap: 0 sucursal.php?slug=; canonical correcto.',
            'siguiente_accion'    => 'Cerrado — AM-SEO-3G-C pospuesto.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-4A',
            'nombre'              => 'Canonical global, titles, H1, FAQ schema',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Fallback canonical www, titles únicos, H1 en detalle, FAQPage condicional, sostenibilidad sin AutoRental.',
            'dependencias'        => ['AM-SEO-3G-B'],
            'ultimo_commit'       => 'b7746a0',
            'evidencia'           => 'EO5144: H1 TOYOTA HILUX 2025, canonical /autos/toyota-hilux-2025/eo5144.',
            'siguiente_accion'    => 'Cerrado tras validación prod.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-DASH-0A',
            'nombre'              => 'Tablero interno de avance',
            'area'                => 'Infraestructura',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Dashboard interno en test/localhost con project-progress.php versionado.',
            'dependencias'        => [],
            'ultimo_commit'       => '1fe318b',
            'evidencia'           => 'test.automarket.com.pa/avance-automarket.php → 200; www → 404; noindex.',
            'siguiente_accion'    => 'Actualizar project-progress.php al cerrar bloques.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-INV-4B',
            'nombre'              => 'URL amigable vehículo',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Alta',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Rutas /autos/{slug}/{placa} vía nginx; legacy /detalle.php?placa= viva; sitemap y canonical alineados.',
            'dependencias'        => ['AM-SEO-4A'],
            'ultimo_commit'       => 'fd0b5db',
            'evidencia'           => 'Prod fd0b5db: EO5144 legacy 200 y /autos/toyota-hilux-2025/eo5144 200, H1 TOYOTA HILUX 2025, canonical amigable, 0 errores; sitemap 144 /autos/, 0 detalle.php?placa=; restart web tras MD5 host≠contenedor.',
            'siguiente_accion'    => 'Cerrado. Deploy nginx: verificar MD5 host vs contenedor; si reload no aplica, restart solo contenedor web.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C-A',
            'nombre'              => 'Módulo blog/contenido listo para mercadeo',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'CMS blog/noticias/novedades operativo; demo oculto en www; estado vacío profesional; Article/BlogPosting schema; sitemap solo publicados reales; isDemoContent conservador.',
            'dependencias'        => ['AM-SEO-4A'],
            'ultimo_commit'       => '16bb81e',
            'evidencia'           => 'Prod 16bb81e: blog 0 Prueba + estado vacío; noticia.php?id=1 → 200 NewsArticle; sitemap 10 noticia/0 prueba/144 autos/20 sucursal; EO5144 intacto; filtro demo no bloquea «Prueba de manejo».',
            'siguiente_accion'    => 'Cerrado. Mercadeo publica desde admin. Futuro opcional: meta por artículo, URLs /blog/{slug}, redirect blog.php?id→noticia.php.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CONT-4C',
            'nombre'              => 'Contenido editorial SEO (epic)',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Módulo listo / contenido pendiente',
            'porcentaje_estimado' => 55,
            'descripcion'         => 'Epic: módulo funcional cerrado en AM-CONT-4C-A; pendiente contenido final de mercadeo, meta dedicada por artículo y URLs amigables futuras.',
            'dependencias'        => ['AM-CONT-4C-A'],
            'ultimo_commit'       => '16bb81e',
            'evidencia'           => '4C-A cerrado prod; artículos reales los carga mercadeo; 10 noticia.php en sitemap.',
            'siguiente_accion'    => 'Mercadeo publica contenido real; evaluar meta/URL amigable en sprint futuro.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-BUGS-4D-A',
            'nombre'              => 'Quick wins footer, menú Seminuevos, sucursales',
            'area'                => 'UX/conversión',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Copyright sin año duplicado, redes sociales coherentes, menú Seminuevos con sucursales, sección sucursales en venta-autos.',
            'dependencias'        => [],
            'ultimo_commit'       => 'd3f5c53',
            'evidencia'           => 'Prod: seminuevos-sucursales 200, menú con /seminuevos-sucursales.php, venta-autos Nuestras Sucursales, © único, 0 TikTok inválido.',
            'siguiente_accion'    => 'Cerrado. TikTok URL real y CTAs siguen en bloqueados_negocio.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-BUGS-4D',
            'nombre'              => 'TikTok, copyright, menú Seminuevos, CTAs',
            'area'                => 'UX/conversión',
            'prioridad'           => 'Media',
            'estado'              => 'Bloqueado por decisión de negocio',
            'porcentaje_estimado' => 50,
            'descripcion'         => 'Epic UX: quick wins cerrados en AM-BUGS-4D-A; pendiente TikTok URL real y decisión CTAs.',
            'dependencias'        => ['AM-BUGS-4D-A'],
            'ultimo_commit'       => 'd3f5c53',
            'evidencia'           => '4D-A en prod; TikTok/CTAs en bloqueados_negocio.',
            'siguiente_accion'    => 'Esperar marketing (TikTok) y decisión negocio (CTAs).',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-A',
            'nombre'              => 'Contactos completos Seminuevos y Renting',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mostrar teléfono, WhatsApp, email y horario desde footer_contact en renting-contactos.php y contactos.php (Seminuevos).',
            'dependencias'        => ['AM-CMS-3B3'],
            'ultimo_commit'       => '17601fc',
            'evidencia'           => 'Prod 17601fc: renting-contactos y contactos?unit=seminuevos → 200; tel/WhatsApp desde footer_contact; 2 bloques contacto responsive (desktop+móvil); formularios e imágenes OK; sitemap/EO5144 intactos.',
            'siguiente_accion'    => 'Cerrado prod. Contactos en admin unidad.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B0',
            'nombre'              => 'Diagnóstico footer builder por columnas',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Diagnóstico aprobado',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Mapa técnico footer: datos, admin, render, riesgos. Decisión aprobada opción C híbrida conservadora.',
            'dependencias'        => ['AM-CMS-5A-A'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Aprobado: builder solo columnas enlaces (N cols); v1 mantiene redes, pagos, contactos, copyright y Conoce también como módulos separados. Sub-bloques B1–B5 definidos.',
            'siguiente_accion'    => 'Cerrado. Siguiente: AM-CMS-5A-B implementación (B1 FooterService) tras aprobación de código.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A',
            'nombre'              => 'CMS Seminuevos-Renting (epic)',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'En desarrollo',
            'porcentaje_estimado' => 58,
            'descripcion'         => 'Epic CMS Seminuevos/Renting: 5A-B1 cerrado; 5A-B2 render dinámico footer en validación.',
            'dependencias'        => ['AM-CMS-3B3'],
            'ultimo_commit'       => 'aa87382',
            'evidencia'           => '5A-B1 cerrado prod; 5A-B2 footer.php getActiveColumns en validación local.',
            'siguiente_accion'    => 'Validar B2 y continuar B3 admin CRUD.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B',
            'nombre'              => 'Footer builder columnas de enlaces',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'En desarrollo',
            'porcentaje_estimado' => 50,
            'descripcion'         => 'Builder N columnas. B1 normalización cerrada; B2 render público dinámico.',
            'dependencias'        => ['AM-CMS-5A-B0'],
            'ultimo_commit'       => 'aa87382',
            'evidencia'           => 'B2: footer.php loop columnas activas; híbrido also_know/social/pagos intacto.',
            'siguiente_accion'    => 'Tras B2: B3 admin CRUD columnas.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B1',
            'nombre'              => 'Normalización FooterService columnas',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Cerrado producción',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'Backend N columnas: normalizeColumns, getActiveColumns, link_type/open_in, legacy recursos, sin admin ni render público.',
            'dependencias'        => ['AM-CMS-5A-B0'],
            'ultimo_commit'       => 'aa87382',
            'evidencia'           => 'Prod aa87382: php -l OK; páginas 200; footer Recursos/Conoce también intacto; EO5144 H1+canonical; sitemap 144/0/20/0.',
            'siguiente_accion'    => 'Cerrado. B2 render dinámico en curso.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5A-B2',
            'nombre'              => 'Render dinámico columnas en footer.php',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'En validación',
            'porcentaje_estimado' => 100,
            'descripcion'         => 'footer.php usa getActiveColumns(); loop N columnas; target blank solo externos; módulos also_know/social/pagos/copyright intactos.',
            'dependencias'        => ['AM-CMS-5A-B1'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Local: 1 col recursos visual igual; multi-col probado; sin admin.',
            'siguiente_accion'    => 'Revisión local; push tras aprobación. Siguiente B3.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-CMS-5B',
            'nombre'              => 'Control ampliado títulos / subtítulos / textos',
            'area'                => 'CMS/editorial',
            'prioridad'           => 'Media',
            'estado'              => 'Pendiente funcional',
            'porcentaje_estimado' => 30,
            'descripcion'         => 'Todos los títulos, subtítulos y bloques de texto editables desde admin.',
            'dependencias'        => ['AM-CMS-5A-B'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Parcial en varias unidades.',
            'siguiente_accion'    => 'Mapear campos faltantes por página.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-AIO-6A',
            'nombre'              => 'Organization schema sameAs / GBP / Wikidata',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Media',
            'estado'              => 'Bloqueado por dato externo',
            'porcentaje_estimado' => 5,
            'descripcion'         => 'Organization schema con sameAs, Wikidata y Google Business Profile.',
            'dependencias'        => ['AM-SEO-4A'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'URLs de perfiles no confirmadas.',
            'siguiente_accion'    => 'Recopilar URLs oficiales con negocio.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-NEG-7A',
            'nombre'              => 'Decisiones negocio: sostenibilidad, fundación, Konzerta, i18n',
            'area'                => 'Contenido/AEO/GEO',
            'prioridad'           => 'Baja',
            'estado'              => 'Bloqueado por decisión de negocio',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'Sostenibilidad vs Fundación, Konzerta, traducción ES/EN y arquitectura institucional.',
            'dependencias'        => [],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Páginas existen; contenido y alcance por definir.',
            'siguiente_accion'    => 'Reunión de negocio para priorizar.',
            'fecha_actualizacion' => '2026-07-03',
        ],
        [
            'codigo'              => 'AM-SEO-3G-C',
            'nombre'              => '301 sucursal.php?slug= → /sucursal/{slug}',
            'area'                => 'SEO técnico',
            'prioridad'           => 'Baja',
            'estado'              => 'Pospuesto',
            'porcentaje_estimado' => 0,
            'descripcion'         => 'Redirección 301 desde URL legacy de sucursal. Explícitamente pospuesto.',
            'dependencias'        => ['AM-SEO-3G-B'],
            'ultimo_commit'       => '—',
            'evidencia'           => 'Sitemap ya sin sucursal.php?slug=.',
            'siguiente_accion'    => 'No implementar sin autorización explícita.',
            'fecha_actualizacion' => '2026-07-03',
        ],
    ],
];
